version: "3"

vars:
  HOVERKRAFT_DEPLOYMENT_ID: 1234
  IMAGE: ttl.sh/fc5845dc-b549-4ffb-85d0-7921a34777a3:1m
  PLATFORMS: linux/amd64,linux/arm64

tasks:
  build:
    cmds:
      - docker buildx build --push --platform {{ .PLATFORMS }} -t {{ .IMAGE }} .

  tests:
    cmds:
      - task test-single-standard
      - task test-single-default
      - task test-multi-standard
      - task test-multi-default

  test-single-standard:
    cmds:
      - >-
        docker run --rm -it \
          -e ARGOCD_ENV_HOVERKRAFT_DEPLOYMENT_ID="{{ .HOVERKRAFT_DEPLOYMENT_ID }}" \
          -v ./tests:/code \
          --workdir /code \
          --entrypoint /hk-tools/single-source.sh \
          {{ .IMAGE }}

  test-single-default:
    cmds:
      - >-
        docker run --rm -it \
          -v ./tests:/code \
          --workdir /code \
          --entrypoint /hk-tools/single-source.sh \
          {{ .IMAGE }}

  test-multi-standard:
    cmds:
      - >-
        docker run --rm -it \
          -e ARGOCD_ENV_HOVERKRAFT_DEPLOYMENT_ID="{{ .HOVERKRAFT_DEPLOYMENT_ID }}" \
          -v ./tests:/code \
          --workdir /code \
          --entrypoint /hk-tools/multi-sources.sh \
          {{ .IMAGE }}

  test-multi-default:
    cmds:
      - >-
        docker run --rm -it \
          -v ./tests:/code \
          --workdir /code \
          --entrypoint /hk-tools/multi-sources.sh \
          {{ .IMAGE }}
