template: |
  # What's Changed
  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...{{image}}-$RESOLVED_VERSION
name-template: "Version {{image}} - $RESOLVED_VERSION"
tag-template: "{{image}}-$RESOLVED_VERSION"
tag-prefix: "{{image}}-"
include-paths:
  - images/{{image}}/*
  - .github/actions/should-build-image/*
  - .github/workflows/__shared-ci.yml
  - .github/workflows/__shared-get-available-images-matrix.yml