name: "Should build the given images"
description: "Check if some files have changed requiring the build of the given images."
author: hoverkraft
branding:
  icon: check-square
  color: blue
inputs:
  images:
    description: |
      Image names located in the 'images' folder.
      Formatted as a JSON array.
      Example: `["php-8", "nodejs-24"]`
    required: true
  base-sha:
    description: "Specify a different base commit SHA used for comparing changes. See https://github.com/tj-actions/changed-files"
    required: false
outputs:
  should-build-images:
    description: |
      Whether or not the images should be built.

      Formatted as a JSON object.

      Example:

      ```json
      {
        "php-8": true,
        "nodejs-24": false
      }
      ```

    value: ${{ steps.changed-images.outputs.should-build-images }}
  changed-files:
    description: "The files related to given images building that have changed, if any"
    value: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}

runs:
  using: "composite"
  steps:
    - if: ${{ github.event_name == 'push' }}
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
        fetch-depth: 2

    - if: ${{ github.event_name != 'push' }}
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
        fetch-depth: 0

    - id: changed-files-paths
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        IMAGES: ${{ inputs.images }}
        ACTION_PATH: ${{ github.action_path }}
      with:
        script: |
          const path = require('path');
          const changedFiles = JSON.parse(process.env.IMAGES).map(image => path.join('images', image, '/'));

          const currentAction = path.join(path.basename(path.dirname(process.env.ACTION_PATH)), path.basename(process.env.ACTION_PATH));
          core.setOutput('current-action', currentAction);
          changedFiles.push(currentAction);

          const currentWorkflow = process.env.GITHUB_WORKFLOW_REF.replace(`${process.env.GITHUB_REPOSITORY}/`, '').replace(/@.*/, '');
          if(currentWorkflow.length > 0) {
            core.setOutput('current-workflow', currentWorkflow);
            changedFiles.push(currentWorkflow);
          }

          core.setOutput('paths', changedFiles.join('\n'));

          const currentWorkflowHasChanged = changedFiles.includes(currentWorkflow);
          core.debug(`Current workflow: ${currentWorkflow} - has changed: ${currentWorkflowHasChanged}`);

    - id: changed-files
      uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # v47.0.1
      with:
        base_sha: ${{ inputs.base-sha }}
        since_last_remote_commit: ${{ github.event_name == 'push' }}
        separator: "\n"
        json: true
        escape_json: false
        files: |
          ${{ steps.changed-files-paths.outputs.paths }}

    - id: changed-images
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        IMAGES: ${{ inputs.images }}
        CURRENT_ACTION: ${{ steps.changed-files-paths.outputs.current-action }}
        CURRENT_WORKFLOW: ${{ steps.changed-files-paths.outputs.current-workflow }}
        CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
      with:
        script: |
          const images = JSON.parse(process.env.IMAGES);
          const changedFiles = process.env.CHANGED_FILES ? JSON.parse(process.env.CHANGED_FILES).map(f => f.trim()).filter(Boolean) : [];

          const currentWorkflowHasChanged = process.env.CURRENT_WORKFLOW ? changedFiles.includes(process.env.CURRENT_WORKFLOW) : false;
          const currentActionHasChanged = changedFiles.includes(process.env.CURRENT_ACTION);

          const shouldBuildImages = {};
          for (const image of images) {
            if (currentActionHasChanged || currentWorkflowHasChanged) {
              shouldBuildImages[image] = true;
              continue;
            }

            const imagePath = `images/${image}/`;
            const hasChanged = changedFiles.some(changedFile => changedFile.startsWith(imagePath));
            shouldBuildImages[image] = hasChanged;
          }

          core.setOutput('should-build-images', JSON.stringify(shouldBuildImages));
