#!/usr/bin/env bash
#MISE description="Generate a brand new ssh key and uses it in git"
#MISE dir="{{ config_root }}"
#USAGE arg "<gpg-id>" var=#true help="GPG id (can be repeated)" {}

set -e -o pipefail

mkdir -p "${HOME}/work/.ssh"
if [ ! -f "${HOME}/work/.ssh/id_ed25519" ]; then
	ssh-keygen -t ed25519 -C 'workshop@hoverkraft.cloud' -f "${HOME}/work/.ssh/id_ed25519" -N ''
	git config --global core.sshCommand "ssh -i ${HOME}/work/.ssh/id_ed25519 -o IdentitiesOnly=yes"
	ssh-keyscan github.com
else
	echo "WARN: SSH key already exists, skipping..."
fi
