[settings]
lockfile = true

[tools]
"aqua:chezmoi" = "2.70.1"
"aqua:cosign" = "3.0.6"
"aqua:crane" = "0.21.5"
"aqua:helm" = "4.1.4"
"aqua:helm-ct" = "3.14.0"
"aqua:helm-docs" = "1.14.2"
"aqua:kubeconform" = "0.7.0"
"aqua:kubectl" = "1.35.3"
"aqua:kubeval" = "0.16.1"
"aqua:kustomize" = "5.8.1"
"aqua:oras" = "1.3.1"
node = "22"
argocd = "3.3.6"
devcontainer-cli = "0.87.0"
fzf = "0.73.1"
krew = "0.5.0"
usage = "3.4.0"

[tasks.generate-ssh-key]
description = 'Generate a brand new ssh-key'
run = """
ssh-keygen -t ed25519 -C 'workshop hoverkraft' -f ${HOME}/work/.ssh/id_ed25519 -N ''
"""
