---
include-paths:
  - "images/ci-helm"
  - ".github/workflows/__prepare-release.yml"
template: |
  # What's Changed
  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...ci-helm-${RESOLVED_VERSION}
name-template: "Version ci-helm - ${RESOLVED_VERSION}"
tag-template: "ci-helm-${RESOLVED_VERSION}"
tag-prefix: "ci-helm-"
prerelease-identifier: "rc"
version-resolver:
  major:
    labels:
      - "release-major"
  minor:
    labels:
      - "release-minor"
  patch:
    labels:
      - "release-patch"
  default: patch
autolabeler:
  - label: "release-major"
    title:
      - "/^BREAKING CHANGE:/"
      - "/^\\w+!:/"
      - "/^\\w+\\(.+\\)!:/"
  - label: "release-minor"
    title:
      - "/^feat:/"
      - "/^feat\\(.+\\):/"
