---
include-paths:
  - "images/testcontainers-node"
  - ".github/workflows/__prepare-release.yml"
template: |
  # What's Changed
  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...testcontainers-node-$RESOLVED_VERSION
name-template: "Version testcontainers-node - $RESOLVED_VERSION"
tag-template: "testcontainers-node-$RESOLVED_VERSION"
tag-prefix: "testcontainers-node-"
prerelease-identifier: "rc"
version-resolver:
  major:
    labels:
      - "release-major"
  minor:
    labels:
      - "release-minor"
  patch:
    labels:
      - "release-patch"
  default: patch
autolabeler:
  - label: "release-major"
    title:
      - "/^BREAKING CHANGE:/"
      - "/^\\w+!:/"
      - "/^\\w+\\(.+\\)!:/"
  - label: "release-minor"
    title:
      - "/^feat:/"
      - "/^feat\\(.+\\):/"
