#!/usr/bin/env bash
#MISE description="Export GPG key"
#MISE dir="{{ config_root }}"
#USAGE flag "--username <username>"

set -e -o pipefail

username="${usage_username?}"

mkdir -p .gpg-keys
gpg --export --armor "${username}"
