#!/usr/bin/env bash
#MISE description="Generate a GPG key"
#MISE dir="{{ cwd }}"

set -e -o pipefail

echo "Generating a new GPG  key"
gpg --generate-key

MYKEY="$(gpg --list-secret-keys --keyid-format=long | awk '/^sec/ {print $2; exit}' | cut -d'/' -f2)"

echo "Reconfigure git to use the new gnupg key"
git config --global user.signingkey "${MYKEY}"
git config --global commit.gpgsign true

echo ""
echo "You new GPG key id is : ${MYKEY}"
