name: "Get available images"
description: "Get the list of available images in the repository"
author: hoverkraft
branding:
  icon: layers
  color: blue

outputs:
  images:
    description: |
      Available images matrix.
      Example:

      ```json
      ["composer","drupal-10"]
      ```
    value: ${{ steps.get-available-images.outputs.images }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - id: get-available-images
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      with:
        script: |
          const path = require('node:path');

          const globber = await glob.create('images/**/Dockerfile');
          const dirs = new Set();
          const imagesDir = path.join(process.env.GITHUB_WORKSPACE, 'images');
          for await (const file of globber.globGenerator()) {
            const dirName = path.relative(imagesDir, path.dirname(file));
            dirs.add(dirName);
          }
          core.setOutput('images', JSON.stringify(Array.from(dirs)));
