# Clean Pull requests resources after close
name: "Pull request - Clean"

on:
  pull_request_target:
    types:
      - closed

permissions:
  contents: read
  packages: write
  issues: read

jobs:
  get-available-images-matrix:
    uses: ./.github/workflows/__shared-get-available-images-matrix.yml

  clean-images:
    needs: get-available-images-matrix
    name: Clean images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.get-available-images-matrix.outputs.images-matrix) }}
    steps:
      - uses: hoverkraft-tech/ci-github-container/actions/docker/prune-pull-requests-image-tags@v0.9.2
        with:
          image: ${{ matrix.image }}
