# Reusable workflow to release changed images.
# Images are grouped by latest released tag SHA to detect which ones need a new release.
# Only images with changes since their latest image-specific tag are released and rebuilt.
# Release tags are planned before builds.
# Releases are created only after image publishing succeeds.
# Should be used from the main release workflow or manual dispatch entrypoint.
name: Release

on:
  workflow_call:
    inputs:
      # jscpd:ignore-start
      runs-on:
        description: |
          JSON array of runner(s) to use.
          See https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job.
        type: string
        default: '["ubuntu-latest"]'
        required: false
      oci-registry:
        description: "OCI registry where to pull and push images."
        type: string
        default: "ghcr.io"
        required: false
      oci-registry-username:
        description: |
          Username used to log against the OCI registry.
          See https://github.com/docker/login-action#usage.
        type: string
        default: ${{ github.repository_owner }}
        required: false
      platforms:
        description: |
          JSON array of platforms to build images for.
          See https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images.
        type: string
        default: '["linux/amd64","linux/arm64"]'
        required: false
      # jscpd:ignore-end
      prerelease:
        description: "Whether the release is a prerelease"
        type: boolean
        default: false
    secrets:
      github-token:
        description: |
          GitHub token with permissions `contents: write`, `pull-requests: read`.
        required: false
      oci-registry-password:
        description: |
          Password or GitHub token (packages:read and packages:write scopes) used to log against the OCI registry.
          Defaults to GITHUB_TOKEN if not provided.
        required: false
  workflow_dispatch:

permissions: {}

concurrency:
  group: release-${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  prepare-images:
    runs-on: ${{ inputs.runs-on && fromJson(inputs.runs-on) || 'ubuntu-latest' }}
    permissions:
      contents: read
    outputs:
      images-matrix: ${{ steps.get-images-matrix.outputs.images-matrix }}
    steps:
      - id: local-workflow-actions
        uses: hoverkraft-tech/ci-github-common/actions/local-workflow-actions@b553a696531fbd36743ccbb0c76c717971b8acdb # 0.35.4
        with:
          actions-path: actions

      - id: get-available-images
        uses: ./../self-workflow/actions/get-available-images

      - id: get-images-matrix
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          IMAGES: ${{ steps.get-available-images.outputs.images }}
        with:
          github-token: ${{ secrets.github-token || secrets.GITHUB_TOKEN || github.token }}
          script: |
            const images = JSON.parse(process.env.IMAGES);

            const tags = await github.paginate(github.rest.repos.listTags, {
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            function getImageLatestTagSha(image) {
              const tagFilter = `${image}-`;
              const imageTags = tags.filter(tag => tag.name.startsWith(tagFilter));

              // Sort tags regarding semver
              imageTags.sort((a, b) => {
                const aVersion = a.name.replace(tagFilter, '');
                const bVersion = b.name.replace(tagFilter, '');
                return bVersion.localeCompare(aVersion, undefined, { numeric: true });
              });

              return imageTags.length ? imageTags[0].commit.sha : null;
            }

            // Group images by their latest tag sha
            const noTagIdentifier = 'no-tag';
            const imagesGroupedByLatestTagSha = {};
            for (const image of images) {
              const latestTagSha = getImageLatestTagSha(image);
              if (latestTagSha) {
                if (!imagesGroupedByLatestTagSha[latestTagSha]) {
                  imagesGroupedByLatestTagSha[latestTagSha] = [];
                }
                imagesGroupedByLatestTagSha[latestTagSha].push(image);
              } else {
                // If no tag found, consider the image needs to be built
                if (!imagesGroupedByLatestTagSha[noTagIdentifier]) {
                  imagesGroupedByLatestTagSha[noTagIdentifier] = [];
                }
                imagesGroupedByLatestTagSha[noTagIdentifier].push(image);
              }
            }

            // Prepare a matrix-like output - images, base-sha
            const imagesMatrix = [];
            for (const [baseSha, images] of Object.entries(imagesGroupedByLatestTagSha)) {
              imagesMatrix.push({
                images,
                "base-sha": baseSha === noTagIdentifier ? null : baseSha,
              });
            }

            core.setOutput('images-matrix', JSON.stringify(imagesMatrix));

  prepare-images-to-release:
    runs-on: ${{ inputs.runs-on && fromJson(inputs.runs-on) || 'ubuntu-latest' }}
    permissions:
      contents: read
    needs: prepare-images
    strategy:
      matrix:
        images: ${{ fromJson(needs.prepare-images.outputs.images-matrix) }}
      fail-fast: false
    steps:
      - id: local-workflow-actions
        uses: hoverkraft-tech/ci-github-common/actions/local-workflow-actions@b553a696531fbd36743ccbb0c76c717971b8acdb # 0.35.4
        with:
          actions-path: actions

      - id: should-build-images
        uses: ./../self-workflow/actions/should-build-images
        with:
          base-sha: ${{ matrix.images.base-sha }}
          images: ${{ toJSON(matrix.images.images) }}

      - id: set-images-to-release
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          BASE_SHA: ${{ matrix.images.base-sha }}
          SHOULD_BUILD_IMAGES: ${{ steps.should-build-images.outputs.should-build-images }}
        with:
          script: |
            const shouldBuildImages = JSON.parse(process.env.SHOULD_BUILD_IMAGES);

            const forceBuild = process.env.BASE_SHA.length === 0;

            const imagesToRelease = Object.entries(shouldBuildImages)
              .filter(([image, shouldBuild]) => forceBuild || shouldBuild === true)
              .map(([image, shouldBuild]) => image);

            if (imagesToRelease.length > 0) {
              core.setOutput('images-to-release', JSON.stringify(imagesToRelease));
            }

      - if: steps.set-images-to-release.outputs.images-to-release
        uses: hoverkraft-tech/ci-github-common/actions/set-matrix-output@b553a696531fbd36743ccbb0c76c717971b8acdb # 0.35.4
        with:
          value: ${{ steps.set-images-to-release.outputs.images-to-release }}
          artifact-name: images-to-release

  get-images-to-release:
    needs: prepare-images-to-release
    runs-on: ${{ inputs.runs-on && fromJson(inputs.runs-on) || 'ubuntu-latest' }}
    outputs:
      images: ${{ steps.get-images-to-release.outputs.images }}
    steps:
      - id: get-matrix-outputs
        uses: hoverkraft-tech/ci-github-common/actions/get-matrix-outputs@b553a696531fbd36743ccbb0c76c717971b8acdb # 0.35.4
        with:
          artifact-name: "images-to-release"

      - id: get-images-to-release
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          IMAGES: ${{ steps.get-matrix-outputs.outputs.result }}
        with:
          script: |
            const images = JSON.parse(process.env.IMAGES);
            core.setOutput('images', JSON.stringify(images.flat()));

  plan-releases:
    name: Plan Release ${{ matrix.image }}
    runs-on: ${{ inputs.runs-on && fromJson(inputs.runs-on) || 'ubuntu-latest' }}
    if: needs.get-images-to-release.outputs.images != '[]'
    permissions:
      contents: read
      pull-requests: read
    needs: get-images-to-release
    strategy:
      matrix:
        image: ${{ fromJson(needs.get-images-to-release.outputs.images) }}
      fail-fast: false
    steps:
      - id: plan-release
        uses: hoverkraft-tech/ci-github-publish/actions/release/plan@84d583ba7b357f9476707f54cf5419d630ae0145 # 0.26.2
        with:
          prerelease: ${{ inputs.prerelease && 'true' || 'false' }}
          working-directory: images/${{ matrix.image }}
          github-token: ${{ secrets.github-token || secrets.GITHUB_TOKEN || github.token }}

      - id: set-planned-release
        if: steps.plan-release.outputs.tag != ''
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          TAG: ${{ steps.plan-release.outputs.tag }}
          IMAGE: ${{ matrix.image }}
        with:
          script: |
            const releaseTag = process.env.TAG.trim();
            const imageName = process.env.IMAGE.trim();
            const imageTag = releaseTag.replace(new RegExp(`^${imageName}-`), '');

            core.setOutput('planned-release', JSON.stringify({
              name: imageName,
              tag: imageTag,
              releaseTag,
            }));

      - if: steps.set-planned-release.outputs.planned-release
        uses: hoverkraft-tech/ci-github-common/actions/set-matrix-output@b553a696531fbd36743ccbb0c76c717971b8acdb # 0.35.4
        with:
          value: ${{ steps.set-planned-release.outputs.planned-release }}
          artifact-name: planned-releases

  prepare-planned-releases:
    name: Prepare Planned Releases
    needs: plan-releases
    runs-on: ${{ inputs.runs-on && fromJson(inputs.runs-on) || 'ubuntu-latest' }}
    outputs:
      images: ${{ steps.get-images-to-build.outputs.images }}
      releases: ${{ steps.get-matrix-outputs.outputs.result }}
    steps:
      - id: get-matrix-outputs
        uses: hoverkraft-tech/ci-github-common/actions/get-matrix-outputs@b553a696531fbd36743ccbb0c76c717971b8acdb # 0.35.4
        with:
          artifact-name: "planned-releases"

      - id: get-images-to-build
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          RELEASES: ${{ steps.get-matrix-outputs.outputs.result }}
        with:
          script: |
            const releases = JSON.parse(process.env.RELEASES || '[]');
            const images = releases.map(release => ({
              name: release.name,
              tag: release.tag,
            }));

            core.setOutput('images', JSON.stringify(images));

  build-images:
    needs: prepare-planned-releases
    if: needs.prepare-planned-releases.outputs.images != '[]'
    uses: ./.github/workflows/docker-build-images.yml
    permissions:
      contents: read
      id-token: write
      issues: read
      packages: write
      pull-requests: write
    with:
      runs-on: ${{ inputs.runs-on || '["ubuntu-latest"]' }}
      oci-registry: ${{ inputs.oci-registry || 'ghcr.io' }}
      oci-registry-username: ${{ inputs.oci-registry-username || github.repository_owner }}
      images: ${{ needs.prepare-planned-releases.outputs.images }}
      platforms: ${{ inputs.platforms || '["linux/amd64","linux/arm64"]' }}
    secrets:
      oci-registry-password: ${{ secrets.oci-registry-password || null }}

  release-images:
    name: Release Image ${{ matrix.release.name }}
    runs-on: ${{ inputs.runs-on && fromJson(inputs.runs-on) || 'ubuntu-latest' }}
    if: needs.prepare-planned-releases.outputs.releases != '[]'
    permissions:
      contents: write
      pull-requests: read
    needs:
      - prepare-planned-releases
      - build-images
    strategy:
      matrix:
        release: ${{ fromJson(needs.prepare-planned-releases.outputs.releases) }}
      fail-fast: false
    steps:
      - id: create-release
        uses: hoverkraft-tech/ci-github-publish/actions/release/create@84d583ba7b357f9476707f54cf5419d630ae0145 # 0.26.2
        with:
          prerelease: ${{ inputs.prerelease && 'true' || 'false' }}
          tag: ${{ matrix.release.releaseTag }}
          target-sha: ${{ github.sha }}
          working-directory: images/${{ matrix.release.name }}
          publish: "true"
          github-token: ${{ secrets.github-token || secrets.GITHUB_TOKEN || github.token }}
